[project]
name = "wpscripts"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "deep-translator>=1.11.4",
    "polib>=1.2.0",
    "tqdm>=4.67.1",
]
